baseURL = "https://www.apify.com/"
contentDir = "content"
title = "Apify Documentation"
theme = "learn"
defaultContentLanguage = "en"
sitemap = { changefreq = "weekly", filename = "sitemap.xml", priority = 0.5 }

[params]
  editURL = "https://github.com/nahid/apify-site/edit/master/content/"
  version = "1.0.0"
  author = "Apify"
  description = "Apify Documentation"
  showVisitedLinks = true
  disableLandingPage = false
  
[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> GitHub"
url = "https://github.com/nahid/apify"
weight = 10

[languages]
[languages.en]
title = "Apify App"
weight = 1
languageName = "English"
